### PR TITLE
Update ocaml syntax

### PR DESCRIPTION
**Pull request by panglesd**
The syntax file was taken from a quite old commit (2020) and had a few bugs. Moreover, it relied on the `ocaml.interface` grammar, which was not loaded when loading the `ocaml` grammar.

This resulted in some things not being highlighted. For instance, in the added test, (taken from some version of  `odoc`), everything inside signature was labelled as `ocaml-source`: 

image

This PR fixes this by adding the `ocaml.interface` syntax and updating the OCaml JSON syntax file to [the latest one at this date](https://github.com/ocamllabs/vscode-ocaml-platform/blob/bde6e565e5da8d4d942e029559f2b27d7ae7525a/syntaxes/ocaml.json). Unfortunately, this file had to be slightly updated, as `tmLanguage` would not accept it as is:

```diff
$ diff ocaml_original.json ocaml_new.json
33,35d32
<         {
<           "comment": "toplevel directives",
<           "patterns": [
84,86c81
<             }
<           ]
<         },
---
>             },
143,144c138,139
<           "beginCaptures": [{ "name": "comment.cinaps.ocaml" }],
<           "endCaptures": [{ "name": "comment.cinaps.ocaml" }],
---
>           "beginCaptures": {"1" : { "name": "comment.cinaps.ocaml" }},
>           "endCaptures": {"1" : { "name": "comment.cinaps.ocaml" }},
336,337c331,332
<           "beginCaptures": [{ "name": "keyword.other.ocaml" }],
<           "endCaptures": [{ "name": "keyword.other.ocaml" }],
---
>           "beginCaptures": {"1" : { "name": "keyword.other.ocaml" }},
>           "endCaptures": {"1" : { "name": "keyword.other.ocaml" }},
343,344c338,339
<           "beginCaptures": [{ "name": "keyword.other.ocaml" }],
<           "endCaptures": [{ "name": "keyword.other.ocaml" }],
---
>           "beginCaptures": {"1" : { "name": "keyword.other.ocaml" }},
>           "endCaptures": { "1" : { "name": "keyword.other.ocaml" }},

```

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @panglesd! Would it make sense to upstream the patch to the VSCode grammar as well?

**Comment by panglesd** [comment]
The file as it is seems to be accepted by VSCode, so I am not sure if VSCode or [textmate-language](https://ocaml.org/p/textmate-language/0.3.1) is the culprit.
Either VSCode has its own syntax/is more forgiving, or if textmate-language is out of date and should be patched, but I don't think there is much value in patching upstream.

**Comment by patricoferris** [comment]
Thanks! When I initially imported the file I also had to make changes to make textmate happy :)) 

Happy to cut a release with these changes and #7 -- are there other grammars/changes you want before doing that?

**Comment by panglesd** [comment]
Thanks!
I do not have more grammar changes, but I wanted to drop the yojson dependency (by generating yojson values instead of parsing them at runtime).
Are you interested in this? I can open a PR about this soon!

**Comment by patricoferris** [comment]
Sounds like a great idea!

**Pull request merged**
