### PR TITLE
Escape HTML entities

### PR DESCRIPTION
**Pull request by cuihtlauac**
When generating a <span> make sure HTML entities are character
encoded in order to avoid being interpreted by the HTML engine.

Character encoding code copied from GitHub repo ocaml/omd, file
src/html.ml

### CODE REVIEW

**Comment by cuihtlauac** [comment]
This should allow to fix issue [496](https://github.com/ocaml/ocaml.org/issues/496) in [ocaml.org](https://github.com/ocaml/ocaml.org)

**Comment by patricoferris** [comment]
Thanks! 

You need to add a `test_md_html.expected` file, then run `dune runtest` and `dune promote` the contents to that file for the new test you have added to test this feature :))

**Comment by patricoferris** [comment]
Great, this looks good. Have you tested this in ocaml.org? Do you need a quick release (anything else you want upstream before cutting another one)?

**Comment by cuihtlauac** [comment]
I haven't tested yet in ocaml.org and haven't noticed anything else at moment other md issues look omd-ish. You can release when convenient.

**Comment by patricoferris** [comment]
Could you test it in Ocaml.org to make sure it works? (no rush!)

**Comment by cuihtlauac** [comment]
Newbie question. Is this the right command in order to bring hilite 0.1.1 in my ocaml.org switch?
```
opam pin add hilite https://github.com/patricoferris/hilite.git#v0.1.1
```
Edited: I was missing the 'v' in the tag name

**Comment by patricoferris** [comment]
Depending on which opam-repository you are using, but hopefully the default has updated so you can do:

```
opam update
opam install -y hilite.0.1.1
```

If you want to pin it I don't know if `#0.1.1` will work, failing that the commit hash is `473fb61f489702f9c5caed0b69f0073c29417564z` so

```
opam pin git+https://github.com/patricoferris/hilite#473fb61f489702f9c5caed0b69f0073c29417564
```

**Comment by cuihtlauac** [comment]
Thanks, pinning the hash helped. Except it's _my_ patch which I need to test :-)
```
opam pin git+https://github.com/cuihtlauac/hilite#38957e008a86362a08ab39001f422b31f7fc4a25
```
Seems to work (from docs/functional-programming)
Screenshot_2022-11-25_13-25-49

**Comment by patricoferris** [comment]
Awesome, thanks!

**Pull request merged**
